### ISSUE TITLE
ontbrekend F.O.

### ISSUE THREAD

**Issue by HjalmarSnoep** [markdooremaal/MDPhoto#1]
Hoi Mark,

Ik heb je schriftelijk advies gevonden, je idee is goedgekeurd (hadden we het in de les al over gehad)
advies:  succes als een groep unieke gebruikers (maak dit specifiek, het is goed om een doel te hebben, ik zal je er niet aan houden, maar jij zelf wel. Ook helpt het bij het vieren van successen: 15 unieke gebruikers: "groei", 30 unieke bezoekers "onverwacht", 50 unieke bezoekers p/m "het begin van een carriere", 100 unieke bezoekers per maand: "begin van patreon campagne".  Zoiets. Dat motiveert, en zorgt ook, dat als je succes krijgt en je doel verschuift, dat je nog even weet hoe je gegroeid bent. Maar dat terzijde..

Je snapt wat ik wil, nu een F.O. met jouw uitwerking. Als je daarvoor een moodboard maakt en concurrentie onderzoek doet, des te beter, maar deze week een F.O.!!!

**Comment by markdooremaal** [comment]
Hi Hjalmar,

Ik heb het functioneel ontwerp toegevoegd. U kunt hem vinden in de Readme die ik zojuist heb aangepast.
