### ISSUE TITLE
F.O. goedgekeurd

### ISSUE THREAD

**Issue by HjalmarSnoep** [markdooremaal/MDPhoto#2]
Ik heb weinig toe te voegen, erg mooi gedaan.
De toevoegingen die ik heb, staan in het F.O bij de links naar de andere documenten als commentaar.
Ga zo door! Lekker gaan bouwen.
Ik hoop dat je er uitkomt met Bulma en Smarty :) maar Bulma ziet er redelijk open uit, dus moet niet echt een probleem worden.

**Comment by markdooremaal** [comment]
Bedankt!
